### ISSUE TITLE
I don't get the coverage results

### ISSUE THREAD

**Issue by radaczynski** [jmhofer/eCobertura#4]
The coverage session view show the folder called "all packages" and the date is updated, but the contents are empty. Eclipse error log shows this:

org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.core.runtime.AssertionFailedException: assertion failed: ContentViewer must have a content provider when input is set.)
    at org.eclipse.swt.SWT.error(SWT.java:3884)
    at org.eclipse.swt.SWT.error(SWT.java:3799)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:137)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3885)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3506)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:113)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:559)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:514)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1311)
Caused by: org.eclipse.core.runtime.AssertionFailedException: assertion failed: ContentViewer must have a content provider when input is set.
    at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
    at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:266)
    at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1634)
    at ecobertura.ui.views.session.CoverageSessionView$$anonfun$createPartControl$2.apply(CoverageSessionView.scala:92)
    at ecobertura.ui.views.session.CoverageSessionView$$anonfun$createPartControl$2.apply(CoverageSessionView.scala:90)
    at ecobertura.ui.views.session.CoverageSessionResetPublisher$$anonfun$fireSessionReset$1.apply(CoverageSessionResetPublisher.scala:39)
    at ecobertura.ui.views.session.CoverageSessionResetPublisher$$anonfun$fireSessionReset$1.apply(CoverageSessionResetPublisher.scala:39)
    at scala.collection.LinearSeqLike$class.foreach(LinearSeqLike.scala:97)
    at scala.collection.immutable.List.foreach(List.scala:46)
    at ecobertura.ui.views.session.CoverageSessionResetPublisher$class.fireSessionReset(CoverageSessionResetPublisher.scala:39)
    at ecobertura.ui.views.session.CoverageSessionModel.fireSessionReset(CoverageSessionModel.scala:38)
    at ecobertura.ui.views.session.CoverageSessionModel.addCoverageSession(CoverageSessionModel.scala:57)
    at ecobertura.ui.core.CoverageResultsUIListener$$anonfun$coverageRunCompleted$2.apply(CoverageResultsUIListener.scala:57)
    at ecobertura.ui.core.CoverageResultsUIListener$$anonfun$coverageRunCompleted$2.apply(CoverageResultsUIListener.scala:57)
    at ecobertura.ui.util.Predef$$anon$2.run(Predef.scala:46)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
    ... 22 more

**Comment by jmhofer** [comment]
Thanks for the stack traces. I'll look into it.

**Comment by radaczynski** [comment]
no problem, if you need more info just drop me a message.

**Comment by jmhofer** [comment]
Have you perhaps closed and reopened the coverage view before this occured?

**Comment by jmhofer** [comment]
I wasn't able to reproduce this, however I've tried to make the plugin more safe against this by implementing a better cleanup and adding an additional check.

**Comment by radaczynski** [comment]
Nope, I have not closed and reopened the coverage view. Perhaps it is because of the project that I am trying to test coverage on (i've had problems with cobertura not being able to instrument classes in that particular project in the past, but I was using maven plugin back then). I will re-test this tomorrow on a simple project with one test case and one class and get back to you on the results.

**Comment by radaczynski** [comment]
hey, I found why I am facing the issue. It only happens on maven projects, even the simplest ones (1 class +  1 test class). On regular java nature projects the plugin works.

**Comment by jmhofer** [comment]
Interesting, thanks! - I'll try to reproduce this on a maven project.

**Comment by jmhofer** [comment]
With the current release, there's no more exception, but it won't record coverage results either...

**Comment by jmhofer** [comment]
On my box, Maven projects do work now after some fixing. You might want to check if this works for you, too, as soon as I put up my next release (0.9.6).

**Comment by radaczynski** [comment]
Will do. When is that going to happen?

**Comment by jmhofer** [comment]
I'm mostly doing a cycle of cleanups right now, so I estimate that I'll have a release version ready within the next two weeks.

**Comment by radaczynski** [comment]
OK, the fix seems to work for me as well with the new release. Thanks! I will post new feature ideas separately...

**Comment by jmhofer** [comment]
Yay! Thanks for the feedback.
